#!/bin/bash
# Regenerates the per-slot stub Service pool (Kotlin classes + manifest entries).
# Index 0 of each slot is the existing P<slot>Service; indexes 1..PER_SLOT-1 are generated here.
set -e
cd "$(dirname "$0")/.."
SLOTS=9; PER_SLOT=${1:-32}
KT=app/src/main/java/com/example/appsandbox/stub/StubServicePool.kt
MF=app/src/main/AndroidManifest.xml
{
  echo "package com.example.appsandbox.stub"
  echo
  echo "// Generated by scripts/gen-stub-services.sh ($PER_SLOT stub Services per slot); do not edit by hand."
  echo
  for ((s = 0; s < SLOTS; s++)); do
    line=""
    for ((i = 1; i < PER_SLOT; i++)); do line+="class P${s}Service$i : BaseStubService(); "; done
    echo "${line% }"
  done
  echo
  echo "internal object StubServicePool {"
  echo "    const val PER_SLOT = $PER_SLOT"
  echo "    val pools: Array<Array<Class<out BaseStubService>>> = arrayOf("
  for ((s = 0; s < SLOTS; s++)); do
    line="        arrayOf(P${s}Service::class.java"
    for ((i = 1; i < PER_SLOT; i++)); do line+=", P${s}Service$i::class.java"; done
    echo "$line)$([ $s -lt $((SLOTS - 1)) ] && echo ,)"
  done
  echo "    )"
  echo "}"
} > $KT
entries=$(for ((s = 0; s < SLOTS; s++)); do for ((i = 1; i < PER_SLOT; i++)); do
  echo "        <service android:name=\".stub.P${s}Service$i\" android:exported=\"false\" android:process=\":p$s\" android:foregroundServiceType=\"specialUse\" />"
done; done)
awk -v entries="$entries" '
  /<!-- stub-service-pool:begin -->/ { print; print entries; skip = 1; next }
  /<!-- stub-service-pool:end -->/ { skip = 0 }
  !skip { print }
' $MF > $MF.tmp && mv $MF.tmp $MF
