param([string]$Serial='7b670025',[string]$HostApk='',[string]$GuestApk='',[string]$HostSha256='',[string]$GuestSha256='')
$ErrorActionPreference='Stop';if($Serial-ne'7b670025'){throw 'serial must be 7b670025'}
$adb='D:/Company/Install/Android/SDK/platform-tools/adb.exe';$root=Split-Path $PSScriptRoot -Parent;$report=Join-Path $root "build/reports/task54/$Serial";New-Item -ItemType Directory -Force $report|Out-Null;. (Join-Path $PSScriptRoot 'task47-adb-helper.ps1')
function A([string[]]$x){Invoke-AdbBounded -Adb $adb -Serial $Serial -CommandArgs $x -TimeoutSec 30 -ReportDir $report}
function V([string]$t,[string]$k){$x=@($t-split"`r?`n"|?{$_-cmatch('^'+[regex]::Escape($k)+'=')});if($x.Count-ne 1){throw "bad key $k"};$x[0].Substring($k.Length+1)}
function ReadReport([string]$p,[string]$id){for($i=0;$i-lt 80;$i++){try{$t=A @('shell','run-as','com.example.appsandbox','cat',$p)}catch{if($_.Exception.Message-notmatch'No such file|not found'){throw};Start-Sleep -Milliseconds 250;continue};if((V $t 'status')-eq'FINAL' -and (V $t 'runId')-ceq$id){return $t};Start-Sleep -Milliseconds 250};throw "timeout $id"}
function Z([string]$t){foreach($k in 'constructorAttempted','guestConstructed','attachExecutorAttempted','attachInvokeAttempted','attachCompleted','guestLifecycle'){if((V $t $k)-ne'false'){throw "$k nonzero"}}}
function GuestPackagePath(){try{return (A @('shell','pm','path','com.example.appsandbox.testguest')).Trim()}catch{if($_.Exception.Message-match'Unknown package|Unable to find package'){return ''};throw}}
if((A @('get-state')).Trim()-ne'device'){throw 'device unavailable'};if((A @('shell','getprop','ro.build.version.sdk')).Trim()-ne'31'){throw 'wrong API'}
if(!$HostApk){$HostApk=Join-Path $root 'app/build/outputs/apk/debug/app-debug.apk'};if(!$GuestApk){$GuestApk=Join-Path $root 'test-guests/GuestTestApp/build/outputs/apk/debug/GuestTestApp-debug.apk'}
if(!(Test-Path $HostApk)-or!(Test-Path $GuestApk)){throw 'APK missing'};$hs=(Get-FileHash $HostApk -Algorithm SHA256).Hash.ToLower();$gs=(Get-FileHash $GuestApk -Algorithm SHA256).Hash.ToLower();if($HostSha256-and$HostSha256.ToLower()-ne$hs){throw 'host SHA mismatch'};if($GuestSha256-and$GuestSha256.ToLower()-ne$gs){throw 'guest SHA mismatch'}
A @('install','-r',$HostApk)|Out-Null;A @('shell','pm','clear','com.example.appsandbox')|Out-Null;A @('push',$GuestApk,'/data/local/tmp/task54-guest.apk')|Out-Null;A @('shell','run-as','com.example.appsandbox','mkdir','-p','files')|Out-Null;A @('shell','run-as','com.example.appsandbox','cp','/data/local/tmp/task54-guest.apk','files/task54-guest.apk')|Out-Null
$setup="setup-$([guid]::NewGuid().ToString('N'))";A @('shell','am','start','-W','-n','com.example.appsandbox/.experiments.act006.api31.Act006SetupActivity','--es','runId',$setup,'--es','stagedApk','/data/data/com.example.appsandbox/files/task54-guest.apk')|Out-Null;$s=ReadReport "files/task51-setup-$setup.result" $setup;if((V $s 'outcome')-ne'IMPORTED'){throw 'import failed'};$instance=V $s 'instanceId'
function Run([string]$c,[string]$id,[string]$why){$p="files/task51-$id.result";A @('shell','run-as','com.example.appsandbox','rm','-f',$p)|Out-Null;A @('shell','am','start','-W','-n','com.example.appsandbox/.experiments.act006.api31.Act006Runner','--es','runId',$id,'--es','caseId',$c,'--es','instanceId',$instance)|Out-Null;$t=ReadReport $p $id;if((V $t 'caseId')-cne$c-or(V $t 'reason')-cne$why){throw "$c reason mismatch"};Z $t;return $t}
$m=[ordered]@{'stale-revision'='STALE_REVISION';'artifact-mismatch'='ARTIFACT_MISMATCH';'missing-class'='MISSING_CLASS';'non-activity'='NON_ACTIVITY_CLASS';'wrong-fingerprint'='WRONG_ADAPTER_FINGERPRINT';'access-denied'='ACCESS_DENIED'};foreach($c in $m.Keys){Run $c "$c-$([guid]::NewGuid().ToString('N'))" $m[$c]|Out-Null};$v=Run 'valid' "valid-$([guid]::NewGuid().ToString('N'))" 'ACCESS_DENIED';$old=(A @('shell','pidof','com.example.appsandbox')).Trim();A @('shell','am','force-stop','com.example.appsandbox')|Out-Null;Run 'valid' "valid-repeat-$([guid]::NewGuid().ToString('N'))" 'ACCESS_DENIED'|Out-Null
$newPid=(A @('shell','pidof','com.example.appsandbox')).Trim();if(!$newPid-or$newPid-eq$old){throw 'repeat PID invalid'};A @('shell','am','start','-W','-n','com.example.appsandbox/.MainActivity')|Out-Null;Start-Sleep -Milliseconds 500;$acts=A @('shell','dumpsys','activity','activities');if($acts-notmatch'(mResumedActivity|topResumedActivity).*com\.example\.appsandbox/.MainActivity'){throw 'Host not resumed'};if((GuestPackagePath)){throw 'Guest installed'};if($acts-match'com\.example\.appsandbox\.testguest'){throw 'Guest record observed'}
"status=PASS`nserial=$Serial`napi=31`nhostSha256=$hs`nguestSha256=$gs`nvalidReason=$(V $v 'reason')`nvalidRuns=2`noldPid=$old`nnewPid=$newPid`nguestInstalled=false`nguestActivityRecord=false"|Set-Content (Join-Path $report result.txt)
