param([string]$Serial='7b670025')
$ErrorActionPreference='Stop';if($Serial-ne'7b670025'){throw 'serial must be 7b670025'}
$adb='D:/Company/Install/Android/SDK/platform-tools/adb.exe';$root=Split-Path $PSScriptRoot -Parent;$report=Join-Path $root "build/reports/task55/$Serial";New-Item -ItemType Directory -Force $report|Out-Null;. (Join-Path $PSScriptRoot 'task47-adb-helper.ps1')
function A([string[]]$x){Invoke-AdbBounded -Adb $adb -Serial $Serial -CommandArgs $x -TimeoutSec 30 -ReportDir $report}
function V($t,$k){$x=@($t-split"`r?`n"|?{$_-match('^'+[regex]::Escape($k)+'=')});if($x.Count-ne 1){throw "bad $k"};$x[0].Substring($k.Length+1)}
function Run($action,$instance='',$apk=''){$id="$action-$([guid]::NewGuid().ToString('N'))";$p="files/task55-$id.result";$args=@('shell','am','start','-W','-n','com.example.appsandbox/.automation.Task55Api31Activity','--es','runId',$id,'--es','action',$action);if($instance){$args+=@('--es','instanceId',$instance)};if($apk){$args+=@('--es','apk',$apk)};A $args|Out-Null;for($i=0;$i-lt 60;$i++){try{$t=A @('shell','run-as','com.example.appsandbox','cat',$p);if((V $t 'status')-eq'FINAL' -and (V $t 'runId')-eq$id){$t|Set-Content (Join-Path $report "$action-$id.txt");return $t}}catch{};Start-Sleep -Milliseconds 250};throw "timeout $action"}
if((A @('shell','getprop','ro.build.version.sdk')).Trim()-ne'31'){throw 'wrong API'};$hostApk=Join-Path $root 'app/build/outputs/apk/debug/app-debug.apk';$guest=Join-Path $root 'test-guests/GuestTestApp/build/outputs/apk/debug/GuestTestApp-debug.apk';A @('install','-r',$hostApk)|Out-Null;A @('shell','pm','clear','com.example.appsandbox')|Out-Null;A @('push',$guest,'/data/local/tmp/task55.apk')|Out-Null;A @('shell','run-as','com.example.appsandbox','mkdir','-p','files')|Out-Null;A @('shell','run-as','com.example.appsandbox','cp','/data/local/tmp/task55.apk','files/task55.apk')|Out-Null
$s=Run 'setup' '' '/data/data/com.example.appsandbox/files/task55.apk';$a=V $s 'instanceA';$b=V $s 'instanceB';$ra=Run 'start' $a;if((V $ra 'outcome')-ne'RUNNING'-or(V $ra 'onCreateCompleted')-ne'1'){throw 'A start failed'};$rb=Run 'start' $b;if((V $rb 'outcome')-ne'RUNNING'){throw 'B start failed'};if((V $ra 'dataRoot')-eq(V $rb 'dataRoot')){throw 'instances not isolated'}
$stop=Run 'stop' $a;if((V $stop 'outcome')-ne'STOPPED'){throw 'stop failed'};$restart=Run 'restart' $a;if((V $restart 'onCreateCompleted')-ne'1'){throw 'restart failed'};Run 'stop' $a|Out-Null;$bad=Run 'throwing' $a;if((V $bad 'reason')-notmatch'^ON_CREATE_FAILED:'){throw 'throwing app not rejected'}
A @('shell','am','force-stop','com.example.appsandbox')|Out-Null;A @('shell','am','start','-W','-n','com.example.appsandbox/.MainActivity')|Out-Null;$acts=A @('shell','dumpsys','activity','activities');if($acts-match'com\.example\.appsandbox\.testguest'){throw 'Guest ActivityRecord'};if((A @('shell','pm','list','packages','com.example.appsandbox.testguest')).Trim()){throw 'Guest installed'}
"status=PASS`nserial=$Serial`napi=31`ninstanceA=$a`ninstanceB=$b`nstartStopRestart=true`nthrowingRejected=true`nisolated=true`nguestInstalled=false`nguestActivityRecord=false`nactivityAttach=false`nactivityLifecycle=false"|Set-Content (Join-Path $report result.txt)
