param([string]$Serial='emulator-5554',[string]$ApkPath='',[string]$GuestApkPath='')
$ErrorActionPreference='Stop'; if($Serial -ne 'emulator-5554'){throw 'API36-only: refusing other device'}
$root=Split-Path $PSScriptRoot -Parent; $adb='D:/Company/Install/Android/SDK/platform-tools/adb.exe'; $out=Join-Path $root "build/reports/task52/$Serial"; New-Item -ItemType Directory -Force $out|Out-Null
. (Join-Path $PSScriptRoot 'task47-adb-helper.ps1'); function A([string[]]$x){Invoke-AdbBounded -Adb $adb -Serial $Serial -CommandArgs $x -TimeoutSec 30 -ReportDir $out}
function ReadReport([string]$path,[string]$id,[string]$caseId){for($i=0;$i -lt 80;$i++){try{$t=(A @('shell','run-as','com.example.appsandbox','cat',$path) | Out-String);if($t -match '(?m)^FINAL=1\s*$' -and $t -match [regex]::Escape("runId=$id") -and $t -match [regex]::Escape("caseId=$caseId")){return $t}}catch{};Start-Sleep -Milliseconds 250};throw "report timeout or non-final report $path"}
if((A @('shell','getprop','ro.build.version.sdk')).Trim() -ne '36'){throw 'device is not API36'}
$hostApk=if($ApkPath){(Resolve-Path $ApkPath).Path}else{Join-Path $root 'app/build/outputs/apk/debug/app-debug.apk'}; $guest=if($GuestApkPath){(Resolve-Path $GuestApkPath).Path}else{Join-Path $root 'test-guests/GuestTestApp/build/outputs/apk/debug/GuestTestApp-debug.apk'}
$hostSha=(Get-FileHash $hostApk -Algorithm SHA256).Hash.ToLowerInvariant(); $guestSha=(Get-FileHash $guest -Algorithm SHA256).Hash.ToLowerInvariant()
A @('install','-r',$hostApk)|Out-Null; A @('shell','pm','clear','com.example.appsandbox')|Out-Null; A @('push',$guest,'/data/local/tmp/task52.apk')|Out-Null; A @('shell','run-as','com.example.appsandbox','mkdir','-p','files')|Out-Null; A @('shell','run-as','com.example.appsandbox','cp','/data/local/tmp/task52.apk','files/task52.apk')|Out-Null
$setup="setup-$([guid]::NewGuid().ToString('N'))"; A @('shell','am','start','-W','-n','com.example.appsandbox/.automation.Task49SetupActivity','--es','runId',$setup,'--es','stagedApk','/data/data/com.example.appsandbox/files/task52.apk')|Out-Null
for($i=0;$i -lt 40;$i++){try{$s=A @('shell','run-as','com.example.appsandbox','cat',"files/task49-setup-$setup.result");if($s -match 'status=PASS'){break}}catch{};Start-Sleep -Milliseconds 250}; $id=[regex]::Match($s,'instanceId=([0-9a-f-]{36})').Groups[1].Value;if(!$id){throw "setup failed: $s"}
function RunCase([string]$scenario,[string]$reason,[bool]$zeroCalls){
 $run="$scenario-$([guid]::NewGuid().ToString('N'))"; $caseId=$run; A @('shell','run-as','com.example.appsandbox','rm','-f',"files/task52-$run.result")|Out-Null; A @('shell','am','start','-W','--activity-clear-task','-n','com.example.appsandbox/.automation.Task49SetupActivity','--es','runId',$run,'--es','caseId',$caseId,'--es','instanceId',$id,'--es','scenario',$scenario,'--es','experiment','act006-api36')|Out-Null
 $t=ReadReport "files/task52-$run.result" $run $caseId; $t|Set-Content (Join-Path $out "$scenario-$run.txt")
 if($t -notmatch "act006.reason=$reason"){throw "$scenario expected $reason`n$t"}; if($t -notmatch 'act006.lifecycleCalls=0'){throw "$scenario lifecycle called"}
 if($zeroCalls -and ($t -notmatch 'act006.constructorAttempted=false' -or $t -notmatch 'act006.attachInvokeAttempted=false')){throw "$scenario was not rejected before calls"}
 return $t
}
$rejected=0; foreach($c in @(@('stale-revision','STALE_REVISION'),@('sha-mismatch','SHA_MISMATCH'),@('missing-class','MISSING_CLASS'),@('non-activity','NON_ACTIVITY'),@('api-mismatch','API_MISMATCH'),@('access-denied','ACCESS_DENIED'))){RunCase $c[0] $c[1] $true|Out-Null;$rejected++}
$valid=RunCase 'valid' 'ACCESS_DENIED' $true
$duplicate="duplicate-$([guid]::NewGuid().ToString('N'))"; foreach($n in 1..2){$dc=$duplicate; A @('shell','run-as','com.example.appsandbox','rm','-f',"files/task52-$duplicate.result")|Out-Null; A @('shell','am','start','-W','--activity-clear-task','-n','com.example.appsandbox/.automation.Task49SetupActivity','--es','runId',$duplicate,'--es','caseId',$dc,'--es','instanceId',$id,'--es','scenario','valid','--es','experiment','act006-api36')|Out-Null; $d=ReadReport "files/task52-$duplicate.result" $duplicate $dc}; if($d -notmatch 'act006.reason=DUPLICATE_LAUNCH' -or $d -notmatch 'act006.attachInvokeAttempted=false'){throw "duplicate launch not rejected`n$d"};$rejected++
$oldPid=(A @('shell','pidof','com.example.appsandbox')).Trim(); A @('shell','am','force-stop','com.example.appsandbox')|Out-Null; $valid2=RunCase 'valid' 'ACCESS_DENIED' $true; $newPid=(A @('shell','pidof','com.example.appsandbox')).Trim(); if(!$newPid -or $newPid -eq $oldPid){throw 'new PID recovery failed'}
$installed=try{(A @('shell','pm','path','com.example.appsandbox.testguest')).Trim()}catch{''};if($installed){throw 'Guest installed'}; $activities=A @('shell','dumpsys','activity','activities');if($activities -match 'com\.example\.appsandbox\.testguest'){throw 'Guest ActivityRecord'}
"status=PASS`napi=36`nhostApk=$hostApk`nhostSha256=$hostSha`nguestApk=$guest`nguestSha256=$guestSha`nvalidRuns=2`nvalidOutcome=ACCESS_DENIED_BEFORE_CONSTRUCTION`nrejected=$rejected`nhiddenInvokeAttempted=0`nhiddenInvokeCompleted=0`noldPid=$oldPid`nnewPid=$newPid`nguestInstalled=false`nguestActivityRecord=false"|Set-Content (Join-Path $out 'result.txt')
