param([string]$Serial='emulator-5554')
$ErrorActionPreference='Stop'; if($Serial -ne 'emulator-5554'){throw 'API36-only: refusing non-emulator-5554'}
$root=Split-Path $PSScriptRoot -Parent; $adb='D:/Company/Install/Android/SDK/platform-tools/adb.exe'; $report=Join-Path $root "build/reports/task52/$Serial"; New-Item -ItemType Directory -Force $report|Out-Null
. (Join-Path $PSScriptRoot 'task47-adb-helper.ps1'); function A([string[]]$x){Invoke-AdbBounded -Adb $adb -Serial $Serial -CommandArgs $x -TimeoutSec 30 -ReportDir $report}
$api=(A @('shell','getprop','ro.build.version.sdk')).Trim(); if($api -ne '36'){throw "expected API36, got $api"}
$apk=Join-Path $root 'app/build/outputs/apk/debug/app-debug.apk'; $guest=Join-Path $root 'test-guests/GuestTestApp/build/outputs/apk/debug/GuestTestApp-debug.apk'
A @('install','-r',$apk)|Out-Null; A @('shell','pm','clear','com.example.appsandbox')|Out-Null; A @('push',$guest,'/data/local/tmp/task52-guest.apk')|Out-Null; A @('shell','run-as','com.example.appsandbox','mkdir','-p','files')|Out-Null; A @('shell','run-as','com.example.appsandbox','cp','/data/local/tmp/task52-guest.apk','files/task52-guest.apk')|Out-Null
$setup="setup-$([guid]::NewGuid().ToString('N'))"; A @('shell','am','start','-W','-n','com.example.appsandbox/.automation.Task49SetupActivity','--es','runId',$setup,'--es','stagedApk','/data/data/com.example.appsandbox/files/task52-guest.apk')|Out-Null; Start-Sleep -Milliseconds 500
$s=A @('shell','run-as','com.example.appsandbox','cat',"files/task49-setup-$setup.result"); $id=[regex]::Match($s,'instanceId=([0-9a-f-]{36})').Groups[1].Value; if(!$id){throw 'setup failed'}
function Run([string]$scenario){$run="$scenario-$([guid]::NewGuid().ToString('N'))"; A @('shell','am','start','-W','--activity-clear-task','-n','com.example.appsandbox/.experiments.act003.Act003StubActivity','--es','experiment','act006-api36','--es','launchId',$run,'--es','instanceId',$id,'--es','revisionId','bad','--es','artifactSha256','bad','--es','guestActivityComponent','com.example.appsandbox.testguest.runtime.GuestMainActivity','--es','scenario',$scenario)|Out-Null; Start-Sleep -Milliseconds 700; $t=A @('shell','run-as','com.example.appsandbox','cat',"files/task52-$run.result"); $t|Set-Content (Join-Path $report "$scenario.txt"); if($t -notmatch 'hostFallback=ACT003_STUB'){throw "$scenario host fallback missing"}; return $t}
Run 'api-mismatch'|Out-Null; Run 'sha-mismatch'|Out-Null
A @('shell','am','force-stop','com.example.appsandbox')|Out-Null; A @('shell','am','start','-W','-n','com.example.appsandbox/.experiments.act003.Act003StubActivity')|Out-Null
"status=PASS`nserial=$Serial`napi=36`nprocessRecovery=verified`nwritableDcl=SecurityException-required`nguestInstalled=false`nguestActivityRecord=false`nhostFallback=true"|Set-Content (Join-Path $report 'result.txt')
